# yamllint disable-file
---


volumes:
  loki-01_data:
  prometheus-01_data:
  grafana-01_data:

networks:
  network-observability:
    external: true
    name: network-observability

version: "3.8"
services:

  loki-01:
    image: docker.io/grafana/loki:latest
    ports:
      - 3001:3001
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./configs/loki/loki-config.yml:/etc/loki/loki-config.yml
      - loki-01_data:/loki:rw
    env_file:
      - ../.env
    networks:
      - network-observability


  alertmanager-01:
    image: docker.io/prom/alertmanager:latest
    ports:
      - 9093:9093
    command: --config.file=/etc/alertmanager/alertmanager.yml
    volumes:
      - ./configs/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    env_file:
      - ../.env
    networks:
      - network-observability

  prometheus-01:
    image: docker.io/prom/prometheus:latest
    ports:
      - 9090:9090
    command: --storage.tsdb.retention.size=512MB --config.file=/etc/prometheus/prometheus.yml
    tty: true
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./configs/prometheus/rules/:/etc/prometheus/rules/
      - prometheus-01_data:/prometheus
    env_file:
      - ../.env
    networks:
      - network-observability


  # alerta-01:
  #   image: docker.io/alerta/alerta-web:latest
  #   ports:
  #     - 8085:8080
  #   volumes:
  #     - ./configs/alerta/alertad.conf:/etc/alertad.conf
  #   env_file:
  #     - ../.env
  #   networks:
  #     - network-observability

  # postgres-01:
  #   image: docker.io/postgres:latest
  #   ports:
  #     - 5432:5432
  #   env_file:
  #     - ../.env
  #   networks:
  #     - network-observability

  grafana-01:
    image: docker.io/grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./configs/grafana/datasources.yml:/etc/grafana/provisioning/datasources/all.yml
      - ./configs/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/all.yml
      - ./configs/grafana/dashboards:/var/lib/grafana/dashboards
      - ./configs/grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana-01_data:/grafana
    env_file:
      - ../.env
    networks:
      - network-observability


  telegraf-01:
    image: docker.io/networktocode/network-collector:latest
    command: telegraf --config /etc/telegraf/telegraf.conf
    tty: true
    volumes:
      - ./configs/telegraf/telegraf-01.conf.toml:/etc/telegraf/telegraf.conf
    ports:
      - 9004:9004
    env_file:
      - ../.env
    networks:
      - network-observability

  telegraf-02:
    image: docker.io/networktocode/network-collector:latest
    command: telegraf --config /etc/telegraf/telegraf.conf
    tty: true
    volumes:
      - ./configs/telegraf/telegraf-02.conf.toml:/etc/telegraf/telegraf.conf
    ports:
      - 9005:9005
    env_file:
      - ../.env
    networks:
      - network-observability

  logstash-01:
    image: docker.io/grafana/logstash-output-loki:latest
    command: -f /home/logstash/logstash.cfg
    volumes:
      - ./configs/logstash/logstash.cfg:/home/logstash/logstash.cfg
      - ./configs/logstash/patterns:/etc/logstash/patterns
    ports:
      - 1514:1514
      - 1515:1515
      - 1516:1516
      - 1517:1517
    env_file:
      - ../.env
    networks:
      - network-observability
